---
- hosts: all
  become: true
  tasks:
  - name: Copy the join command to server location
    copy: src=/tmp/join_command dest=/tmp/join_command mode=0777
    
  - name: Join the node to cluster
    become: true
    command: sh /tmp/join_command
